### PR TITLE
Data Ingestion

### PR DESCRIPTION
**Pull request by annaoliinyk**

### CODE REVIEW

**Review by AnaKovaGH — CHANGES_REQUESTED** [review]
1. Remove clonned repo and just get data from API
2. Change your code due to OOP SOLID principles.
3. Create a separate dir with configs.

**Comment by annaoliinyk** [comment]
This was fixed

**Review by AnaKovaGH — CHANGES_REQUESTED** [review]
1. Rename local and remote branch from "extract" to more descriptive name.
2. Remove configs/ from .gitignore
3. Make __init__.py as empty file.
4. Rename extract_data_from_OpenSkyApi to some noun like OpenSkyDataExtractor.
5. Create a separate folder with configs files.
6. Add OOP (classes) to your code.
7. Uncomment saving files to json.
8. Remove comment before logging.
9. Add logging before main() start. 1 - Job start timestamp, 2 - Job description (data ingest), 3 - Job finish timestamp).

**Comment by annaoliinyk** [comment]
Fixed, see https://github.com/annaoliinyk/SoftServe-Internship_ETL-project/pull/3

**Pull request closed without merging**
